### ISSUE TITLE
Any license?

### ISSUE THREAD

**Issue by Crsuh2er0** [layou233/MCPacket#1]
Wow its so great. Could u plz add a license so that  i can use it?

**Comment by layou233** [comment]
well I don't think this library has been completed yet. The encryption part is not finished and the whole library hasn't been tested in production environment.  
This project originated from `Tnze/go-mc` but the maintenance has temporarily stalled because I'm busy with my other works. I'll add MIT license later but there are something to attention:  
- The library hasn't been uploaded to Maven so you should download it by yourself.  
- Not tested, use at your own risk.  
- Issues and PR are welcome but issues may not receive fixes in a short time.  
- Have a good day! XD
